### ISSUE TITLE
Web engine version?

### ISSUE THREAD

**Issue by den7007** [flathub/com.github.rssguard#24]
Would it be possible to have the web engine enabled version instead of the lite version?

https://github.com/martinrotter/rssguard/blob/master/resources/docs/Documentation.md#webb

**Comment by martinrotter** [comment]
Yes, if somebody packaged it. I have almost zero ability in making flatpaks. Somebody else would have to step in.

**Comment by guihkx** [comment]
Working on this. 

@martinrotter Can you please hold the 4.2.2 release? I'm preparing a pull request.

**Comment by martinrotter** [comment]
I just released 4.2.2 3 hours ago? What do you mean hold?

**Comment by guihkx** [comment]
I meant holding the Flatpak release of 4.2.2, since we're still on 4.2.1.

However, this might be harder than I anticipated. I already have a working build with working WebEngine support here:

![image](https://user-images.githubusercontent.com/626206/165936630-746b6494-16ad-426f-b401-f8c6acedf42d.png)

However, it's still lacking npm support and it seems a bit complicated to bundle it, so feel free to release 4.2.2 with no WebEngine support while I figure out a way around this...

**Comment by guihkx** [comment]
> but they can install NPM system-wide etc.

Unfortunately, in order for that approach to work on Flatpak apps, we'd have to expose the host filesystem, and to be honest I'm not a big fan of that, especially because we're dealing with third-party npm packages...

How about this: If I can't get a working build with bundled npm support within the next 24 hours, I'll send a pull request with only WebEngine support.

P.S.: I've converted the JSON manifest to YAML for easier readability and maintainability, hope that's okay with you!
